version: "2"

run:
  timeout: 1m
  tests: true
  modules-download-mode: readonly
  go: "1.22"

output:
  formats:
    - format: colored-line-number
      path: stdout
  sort-results: true

linters:
  enable:
    - bodyclose
    - copyloopvar
    - errcheck
    - errorlint
    - exhaustive
    - gosec
    - govet
    - ineffassign
    - nilerr
    - noctx
    - staticcheck
    - typecheck
    - unused

    # Code quality
    - cyclop
    - dupl
    - funlen
    - gocognit
    - goconst
    - gocritic
    - goimports # Formats imports
    - revive # Replacement for golint
    - unconvert # Removes unnecessary type conversions
    - unparam # Reports unused parameters
    - usestdlibvars

    # Style
    - gofumpt
    - misspell
    - whitespace
    - godot

    # Modern Go
    - durationcheck
    - makezero
    - nilnil
    - usetesting

linters-settings:
  cyclop:
    max-complexity: 12
  errcheck:
    check-type-assertions: true
    check-blank: true
  exhaustive:
    default-signifies-exhaustive: false
  funlen:
    lines: 100
    statements: 50
  gocognit:
    min-complexity: 20
  goconst:
    min-len: 3
    min-occurrences: 3
  gocritic:
    enabled-tags:
      - diagnostic
      - performance
      - style
    disabled-checks:
      - hugeParam
      - rangeValCopy
  gocyclo:
    min-complexity: 15
  godot:
    scope: declarations
  gofumpt:
    extra-rules: true
  govet:
    enable:
      - shadow
  lll:
    line-length: 120
  nolintlint:
    allow-unused: false
    require-explanation: true
    require-specific: true
  revive:
    rules:
      - name: indent-error-flow
      - name: unused-parameter
  depguard:
    rules:
      standard:
        files:
          - $all
        allow:
          - $gostd
        deny:
          - pkg: github.com/pkg/errors
            desc: "Use standard errors package instead"
      logging:
        files:
          - $all
        deny:
          - pkg: log
            desc: "Use a structured logger instead"

issues:
  max-issues-per-linter: 10
  max-same-issues: 5
  exclude-rules:
    - source: "^//go:generate "
      linters: [lll]
    - path: _test\.go
      linters:
        - dupl
        - funlen
        - gosec
        - noctx
    - path: /vendor/
      linters:
        - all
    - path: test/
      linters:
        - goconst
